// What is javascript.
// Javascript is a server-side and client side scripting and object oriented langauge used create web application and desktop application
// also used to create andriod app using JS library.

// Features.
// 1.Server side(backend) and client side(frontend) supportive.
// 2.Easily integreted with HTML-CSS
// 3.Dynamically typed language.
// 4.Event-Driven programming.
// 5.synchronous(sync) and asynchronous(async)
// 6.By default single threaded and also used as multithreaded.
// 7.Top Libraries : Reactjs , vuejs , angularjs , electronjs.

// Type of applying javascript:
// 1.Internal JS
// 2.External JS


var name1="IQ-INDIA"
document.write(name1)
document.write("<hr>")
document.write("How are you")
