// Variables:
// Variable is a location used to store data 
// which is easly accessible in future use.

//---- var 
// var x=34
// var x=40
// var x=50
// console.log(x)
// Reassigning valid

// ----- let
// let n=90;
// n=78
// n=90;
// console.log(`Output : ${n}`)
// Reassigning invalid, but if variable with let keyword declared then reassigning possible

// ----- const
// const pi=3.14;
// console.log(pi)

// let n=50;
// n=60
// console.log(n)

// ------------- Rules of variables.

// 1.Variable can not startwith any number.
// let 56=90 // error

// 2.Variable can not startwith any symbol, excluded(_)
// let _34=89;

// let last_name="dev"
// console.log(last_name)

// 3.Variable can not include whitespaces.

// 4.Variables in javscript are case-senstive.

// let a=45;
// let A=45;

// --------------------------------------
let x=23
let y=45
res=x+y
console.log("Result:",res)

// Data Types in javascript.
// 1.Primitive data types.
// 1.Numbers -> float,positive,negative
// 2.Strings.
// 3.undefined.
// 4.null.
// 5.Boolean.

